services:
  mvcmovie:
    image: mvcmovie
    build:
      context: ./MvcMovie
      dockerfile: Dockerfile
    env_file:
      - .env 
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__MvcMovieContext=${MVCMOVIE_CONNECTIONSTRING}
    ports:
      - "8081:80"  # Expose the app on port 8081
    depends_on:
      - movies_db

  movies_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"   # Expose the database on port 5433
